target-version = "py312"

[lint]
select = ["ALL"]
ignore = [
  "D",
  "E501",
  "PGH003",
  # Parameter is part of public interface
  "ARG003",
  # Trivial parameters, no need to annotate
  "ANN101",
  "ANN102",
  # Boolean param is useful
  "FBT001",
  "FBT002",
]

[lint.flake8-tidy-imports]
ban-relative-imports = "all"

[lint.flake8-builtins]
builtins-ignorelist = ["type"]

[lint.isort]
split-on-trailing-comma = false

[lint.pycodestyle]
max-doc-length = 88
